# Generated by Django 4.1.7 on 2023-07-07 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_error",
                    models.BooleanField(default=False, verbose_name="Была ошибка?"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "from_email",
                    models.CharField(
                        default="Denns2002@yandex.ru", max_length=255, verbose_name="От"
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
