# Generated by Django 4.1.7 on 2023-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="error",
            field=models.TextField(blank=True, null=True, verbose_name="Ошибка"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="from_email",
            field=models.CharField(
                blank=True,
                default="Denns2002@yandex.ru",
                max_length=255,
                null=True,
                verbose_name="От",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_error",
            field=models.BooleanField(default=False, verbose_name="Была ошибка"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="subject",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Тема письма"
            ),
        ),
    ]
