# Generated by Django 4.1.7 on 2023-07-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs_groups", "0006_alter_club_managers_alter_group_trainers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("reg_start", models.DateField(verbose_name="Начало регистрации")),
                ("reg_end", models.DateField(verbose_name="Окончание регистрации")),
                ("date_start", models.DateField(verbose_name="Дата начала")),
                ("date_end", models.DateField(verbose_name="Дата окончания")),
                ("about", models.TextField(verbose_name="Описание")),
                (
                    "is_attestation",
                    models.BooleanField(default=False, verbose_name="Аттестация"),
                ),
                (
                    "attestation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время аттестации"
                    ),
                ),
                (
                    "is_seminar",
                    models.BooleanField(default=False, verbose_name="Семинар"),
                ),
                (
                    "seminar_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время семинара"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "addresses",
                    models.ManyToManyField(
                        blank=True, to="clubs_groups.address", verbose_name="Адреса"
                    ),
                ),
                (
                    "co_organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_organizers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Соорганизаторы",
                    ),
                ),
                (
                    "organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организаторы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="PlannedEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs_groups.group",
                    ),
                ),
            ],
        ),
    ]
