# Generated by Django 4.1.7 on 2023-03-23 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reg_start", models.DateTimeField()),
                ("reg_end", models.DateTimeField()),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("place", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("is_attestation", models.BooleanField(default=False)),
                ("is_seminar", models.BooleanField(default=False)),
                (
                    "co_organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_organizers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(blank=True, related_name="members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
