# Generated by Django 4.1.7 on 2023-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="reg_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="reg_start",
            field=models.DateField(),
        ),
    ]
