# Generated by Django 4.1.7 on 2023-04-18 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cities", "0006_alter_address_options_alter_apt_options_and_more"),
        ("events", "0003_alter_event_reg_end_alter_event_reg_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="place",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.address",
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="about",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="co_organizers",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_organizers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Соорганизаторы",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_end",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_start",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_attestation",
            field=models.BooleanField(default=False, verbose_name="Аттестация"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_seminar",
            field=models.BooleanField(default=False, verbose_name="Семинар"),
        ),
        migrations.AlterField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организаторы",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reg_end",
            field=models.DateField(verbose_name="Окончание регистрации"),
        ),
        migrations.AlterField(
            model_name="event",
            name="reg_start",
            field=models.DateField(verbose_name="Начало регистрации"),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
        ),
    ]
