# Generated by Django 4.1.7 on 2023-04-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_remove_event_place_event_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address',
            new_name='addresses',
        ),
    ]
