# Generated by Django 4.1.7 on 2023-04-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0007_rename_group_id_groupmember_group_and_more"),
        ("events", "0005_rename_address_event_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.event"),
                ),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clubs.group"),
                ),
            ],
        ),
    ]
