# Generated by Django 4.1.7 on 2023-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_statement_statementmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
