# Generated by Django 4.1.7 on 2023-05-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_statement_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementmember",
            name="statement",
        ),
        migrations.AddField(
            model_name="statement",
            name="statement_members",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.statementmember",
            ),
            preserve_default=False,
        ),
    ]
