# Generated by Django 4.1.7 on 2023-05-04 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_remove_statementmember_statement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementmember",
            name="member",
        ),
        migrations.DeleteModel(
            name="Statement",
        ),
        migrations.DeleteModel(
            name="StatementMember",
        ),
    ]
