# Generated by Django 4.1.7 on 2023-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_remove_statementmember_member_delete_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attestation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время аттестации"),
        ),
        migrations.AddField(
            model_name="event",
            name="seminar_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время семинара"),
        ),
    ]
