# Generated by Django 4.1.7 on 2023-04-18 06:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phone",
            options={"verbose_name": "Телефон", "verbose_name_plural": "Телефоны"},
        ),
        migrations.AlterField(
            model_name="phone",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
