# Generated by Django 4.1.7 on 2023-04-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubphone',
            old_name='club',
            new_name='clubs',
        ),
        migrations.RenameField(
            model_name='userphone',
            old_name='profile',
            new_name='profiles',
        ),
    ]
