# Generated by Django 4.1.7 on 2023-07-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("photos", "0002_alter_photo_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "trainers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_fee",
                    models.BooleanField(
                        default=False, verbose_name="Ежегодная выплата"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs_groups.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        unique=True,
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник группы",
                "verbose_name_plural": "Участники группы",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("info", models.TextField(verbose_name="Информация")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "addresses",
                    models.ManyToManyField(
                        blank=True, to="clubs_groups.address", verbose_name="Адреса"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="clubs_groups.group", verbose_name="Группы"
                    ),
                ),
                (
                    "managers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                        verbose_name="Руководители",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, to="photos.photo", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клуб",
                "verbose_name_plural": "Клубы",
            },
        ),
    ]
