# Generated by Django 4.1.7 on 2023-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("clubs_groups", "0002_remove_club_managers_alter_group_trainers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs_groups.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "managers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                        verbose_name="Руководители",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководители",
            },
        ),
        migrations.DeleteModel(
            name="GroupManagers",
        ),
    ]
