# Generated by Django 4.1.7 on 2023-07-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("clubs_groups", "0003_clubmanager_delete_groupmanagers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="trainers",
        ),
        migrations.CreateModel(
            name="GroupTrainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs_groups.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "trainers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.profile",
                        verbose_name="Тренера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренер группы",
                "verbose_name_plural": "Тренера группы",
            },
        ),
    ]
