# Generated by Django 4.1.7 on 2023-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("clubs_groups", "0004_remove_group_trainers_grouptrainer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouptrainer",
            name="group",
        ),
        migrations.RemoveField(
            model_name="grouptrainer",
            name="trainers",
        ),
        migrations.AddField(
            model_name="club",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="profiles.profile",
                verbose_name="Руководители",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="trainers",
            field=models.ManyToManyField(
                blank=True, null=True, to="profiles.profile", verbose_name="Тренера"
            ),
        ),
        migrations.DeleteModel(
            name="ClubManager",
        ),
        migrations.DeleteModel(
            name="GroupTrainer",
        ),
    ]
