# Generated by Django 4.1.7 on 2023-07-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("clubs_groups", "0005_remove_grouptrainer_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="managers",
            field=models.ManyToManyField(
                blank=True, to="profiles.profile", verbose_name="Руководители"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="trainers",
            field=models.ManyToManyField(
                blank=True, to="profiles.profile", verbose_name="Тренера"
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                verbose_name="Профиль",
            ),
        ),
    ]
