# Generated by Django 4.1.7 on 2023-07-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_profile_mid_name"),
        ("clubs_groups", "0007_remove_club_addresses_delete_address_club_addresses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                unique=True,
                verbose_name="Профиль",
            ),
        ),
    ]
