# Generated by Django 4.1.7 on 2023-05-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profile", "0001_initial"),
        ("photos", "0001_initial"),
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("number", models.IntegerField(unique=True, verbose_name="Номер")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Children's", "Детская"), ("Adult", "Взрослая")],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profile.profile",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_fee",
                    models.BooleanField(
                        default=False, verbose_name="Ежегодная выплата"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                        unique=True,
                        verbose_name="Профиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник группы",
                "verbose_name_plural": "Участники группы",
            },
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("price", models.IntegerField(default=0, verbose_name="Стоимость")),
                ("paid", models.IntegerField(default=0, verbose_name="Выплачено")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.groupmember",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задолжность",
                "verbose_name_plural": "Задолжности",
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("info", models.TextField(verbose_name="Информация")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "addresses",
                    models.ManyToManyField(
                        blank=True, to="cities.address", verbose_name="Адреса"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="clubs.group", verbose_name="Группы"
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, to="photos.photo", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клуб",
                "verbose_name_plural": "Клубы",
            },
        ),
    ]
