# Generated by Django 4.1.7 on 2023-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[("Детская", "Детская"), ("Взрослая", "Взрослая")],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
