# Generated by Django 4.1.7 on 2023-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="type",
            field=models.CharField(
                choices=[
                    ("Группа", "Группа"),
                    ("Свободный", "Свободный"),
                    ("Мероприятие", "Мероприятие"),
                ],
                default="Группа",
                max_length=255,
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
    ]
