# Generated by Django 4.1.7 on 2024-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0002_statementmember_fio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementmember",
            name="fio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
