# Generated by Django 4.1.7 on 2024-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0003_alter_statementmember_fio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementmember",
            name="fio",
        ),
        migrations.AddField(
            model_name="statement",
            name="fio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
