# Generated by Django 4.1.7 on 2023-05-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0002_alter_statementmember_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
