# Generated by Django 4.1.7 on 2023-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0004_statement_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="statements/"),
        ),
    ]
