# Generated by Django 4.1.7 on 2023-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0007_remove_statement_statement_members_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementmember",
            name="statement",
        ),
        migrations.AddField(
            model_name="statement",
            name="statement_members",
            field=models.ManyToManyField(to="statements.statementmember"),
        ),
    ]
