# Generated by Django 4.1.7 on 2023-05-10 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0008_remove_statementmember_statement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="statement_members",
        ),
        migrations.AddField(
            model_name="statementmember",
            name="statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="statements.statement",
            ),
        ),
    ]
