# Generated by Django 4.1.7 on 2023-05-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_remove_statementmember_member_delete_statement_and_more"),
        ("statements", "0009_remove_statement_statement_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
        ),
    ]
