# Generated by Django 4.1.7 on 2023-05-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_profile_photos"),
        ("statements", "0011_statement_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementmember",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
            ),
        ),
    ]
