# Generated by Django 4.1.7 on 2023-05-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0012_alter_statementmember_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="file",
        ),
        migrations.AddField(
            model_name="statement",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
