# Generated by Django 4.1.7 on 2023-05-11 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statements", "0013_remove_statement_file_statement_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="creator",
        ),
    ]
