# Generated by Django 4.1.7 on 2023-05-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("6 kyu child", "6 кю детский"),
                            ("5 kyu child", "5 кю детский"),
                            ("4 kyu child", "4 кю детский"),
                            ("3 kyu child", "3 кю детский"),
                            ("2 kyu child", "2 кю детский"),
                            ("1 kyu child", "1 кю детский"),
                            ("5 kyu", "5 кю"),
                            ("4 kyu", "4 кю"),
                            ("3 kyu", "3 кю"),
                            ("2 kyu", "2 кю"),
                            ("1 kyu", "1 кю"),
                            ("1 dan", "1 дан"),
                            ("2 dan", "2 дан"),
                            ("3 dan", "3 дан"),
                            ("4 dan", "4 дан"),
                            ("5 dan", "5 дан"),
                            ("6 dan", "6 дан"),
                            ("7 dan", "7 дан"),
                            ("8 dan", "8 дан"),
                            ("9 dan", "9 дан"),
                            ("10 dan", "10 дан"),
                            ("Dosyu", "Досю"),
                        ],
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ранг",
                "verbose_name_plural": "Ранги",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Trainer", "Trainer"),
                            ("Student", "Student"),
                            ("Supervisor", "Supervisor"),
                        ],
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "mid_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отчество"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo/%Y/%m/%d/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "next_rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_rank",
                        to="profile.rank",
                        verbose_name="Следующий Ранг",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, to="photos.photo", verbose_name="Фото"
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rank",
                        to="profile.rank",
                        verbose_name="Ранг",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, to="profile.role", verbose_name="Роли"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
