# Generated by Django 4.1.7 on 2023-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rank",
            name="price",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(
                choices=[
                    ("6 kyu child", "6 кю детский"),
                    ("5 kyu child", "5 кю детский"),
                    ("4 kyu child", "4 кю детский"),
                    ("3 kyu child", "3 кю детский"),
                    ("2 kyu child", "2 кю детский"),
                    ("1 kyu child", "1 кю детский"),
                    ("5 kyu", "5 кю"),
                    ("4 kyu", "4 кю"),
                    ("3 kyu", "3 кю"),
                    ("2 kyu", "2 кю"),
                    ("1 kyu", "1 кю"),
                    ("1 dan", "1 дан"),
                    ("2 dan", "2 дан"),
                    ("3 dan", "3 дан"),
                    ("4 dan", "4 дан"),
                    ("5 dan", "5 дан"),
                    ("Dosyu", "Досю"),
                ],
                max_length=255,
                verbose_name="Название",
            ),
        ),
    ]
