# Generated by Django 4.1.7 on 2023-04-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
