# Generated by Django 4.1.7 on 2023-04-18 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_remove_clubphoto_photo_remove_userphoto_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userphoto",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="userphoto",
            name="profile",
        ),
        migrations.DeleteModel(
            name="ClubPhoto",
        ),
        migrations.DeleteModel(
            name="UserPhoto",
        ),
    ]
