# Generated by Django 4.1.7 on 2023-03-09 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="timezone",
        ),
    ]
