# Generated by Django 4.1.7 on 2023-04-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0003_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="street",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.city",
            ),
        ),
    ]
