# Generated by Django 4.1.7 on 2023-04-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0005_apt_house_alter_region_options_remove_street_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="apt",
            options={
                "verbose_name": "Номер квартиры",
                "verbose_name_plural": "Номера квартир",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Страна", "verbose_name_plural": "Страны"},
        ),
        migrations.AlterModelOptions(
            name="house",
            options={
                "verbose_name": "Номер дома",
                "verbose_name_plural": "Номера домов",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Регион", "verbose_name_plural": "Регионы"},
        ),
        migrations.AlterModelOptions(
            name="street",
            options={"verbose_name": "Улица", "verbose_name_plural": "Улицы"},
        ),
        migrations.RemoveField(
            model_name="apt",
            name="name",
        ),
        migrations.RemoveField(
            model_name="house",
            name="name",
        ),
        migrations.AddField(
            model_name="apt",
            name="number",
            field=models.CharField(default=0, max_length=255, verbose_name="Номер квартиры"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="number",
            field=models.CharField(default=0, max_length=255, verbose_name="Номер дома"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="apt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.apt",
                verbose_name="Номер квартиры",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.house",
                verbose_name="Номер дома",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.street",
                verbose_name="Улица",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="city",
            name="postal_code",
            field=models.CharField(max_length=255, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="region",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="street",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
