# Generated by Django 4.1.7 on 2023-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
    ]
