# Generated by Django 4.1.7 on 2023-04-18 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0020_alter_profile_options_alter_rank_options_and_more"),
        ("clubs", "0002_alter_club_options_club_addresses_alter_club_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("number", models.IntegerField(unique=True, verbose_name="Номер")),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clubs.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "trainers",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Тренеры"),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_fee",
                    models.BooleanField(default=False, verbose_name="Ежегодная выплата"),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.group",
                        verbose_name="ID Группы",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.profile",
                        verbose_name="ID Профиля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник группы",
                "verbose_name_plural": "Участники группы",
            },
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("price", models.IntegerField(default=0, verbose_name="Стоимость")),
                ("paid", models.IntegerField(default=0, verbose_name="Выплачено")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clubs.groupmember",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задолжность",
                "verbose_name_plural": "Задолжности",
            },
        ),
    ]
