# Generated by Django 4.1.7 on 2023-04-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_profile_options_alter_rank_options_and_more"),
        ("clubs", "0003_group_groupmember_debts"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="slug",
            field=models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
                verbose_name="Профиль",
            ),
        ),
    ]
