# Generated by Django 4.1.7 on 2023-04-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='debts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
