# Generated by Django 4.1.7 on 2023-05-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0024_alter_profile_photos"),
        ("clubs", "0007_rename_group_id_groupmember_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="trainers",
        ),
        migrations.AddField(
            model_name="group",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.profile",
                verbose_name="Тренер",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="type",
            field=models.CharField(
                choices=[("Children's", "Детская"), ("Adult", "Взрослая")],
                default=0,
                max_length=20,
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.profile",
                unique=True,
                verbose_name="Профиль",
            ),
        ),
    ]
