# Generated by Django 4.1.7 on 2023-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_remove_userphoto_photo_remove_userphoto_profile_and_more"),
        ("clubs", "0008_remove_group_trainers_group_trainer_group_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="photos",
            field=models.ManyToManyField(
                blank=True, to="photos.photo", verbose_name="Фото"
            ),
        ),
    ]
