# Generated by Django 4.1.7 on 2023-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0009_alter_club_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
