# Generated by Django 4.1.7 on 2023-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0008_remove_group_trainers_group_trainer_group_type_and_more"),
        ("clubs", "0011_alter_groupmember_group_alter_groupmember_profile"),
    ]

    operations = []
