# Generated by Django 4.1.7 on 2023-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0012_merge_20230510_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
