# Generated by Django 4.1.7 on 2023-07-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="link",
            field=models.ImageField(
                unique=True, upload_to="photo/%Y/%m/%d/", verbose_name="Ссылка"
            ),
        ),
    ]
