# Generated by Django 4.1.7 on 2023-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_city_club_country_profile_rank_role_userrank_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AddField(
            model_name="profile",
            name="groups",
            field=models.ManyToManyField(to="user.group"),
        ),
    ]
