# Generated by Django 4.1.7 on 2023-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photo/%Y/%m/%d/"),
        ),
    ]
