# Generated by Django 4.1.7 on 2023-03-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("user", "0007_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.region",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.city",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities.country",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(
                choices=[
                    ("10 kyu", "10 кю"),
                    ("9 kyu", "9 кю"),
                    ("8 kyu", "8 кю"),
                    ("7 kyu", "7 кю"),
                    ("6 kyu", "6 кю"),
                    ("5 kyu", "5 кю"),
                    ("4 kyu", "4 кю"),
                    ("3 kyu", "3 кю"),
                    ("2 kyu", "2 кю"),
                    ("1 kyu", "1 кю"),
                    ("1 dan", "1 дан"),
                    ("2 dan", "2 дан"),
                    ("3 dan", "3 дан"),
                    ("4 dan", "4 дан"),
                    ("5 dan", "5 дан"),
                    ("6 dan", "6 дан"),
                    ("7 dan", "7 дан"),
                    ("8 dan", "8 дан"),
                    ("9 dan", "9 дан"),
                    ("10 dan", "10 дан"),
                    ("Dosyu", "Досю"),
                ],
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
