# Generated by Django 4.1.7 on 2023-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_birth_date_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mid_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
