# Generated by Django 4.1.7 on 2023-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_photo_profile_avatar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
