# Generated by Django 4.1.7 on 2023-03-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_slug_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
