# Generated by Django 4.1.7 on 2023-03-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.rank'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('6 kyu child', '6 кю детский'), ('5 kyu child', '5 кю детский'), ('4 kyu child', '4 кю детский'), ('3 kyu child', '3 кю детский'), ('2 kyu child', '2 кю детский'), ('1 kyu child', '1 кю детский'), ('5 kyu', '5 кю'), ('4 kyu', '4 кю'), ('3 kyu', '3 кю'), ('2 kyu', '2 кю'), ('1 kyu', '1 кю'), ('1 dan', '1 дан'), ('2 dan', '2 дан'), ('3 dan', '3 дан'), ('4 dan', '4 дан'), ('5 dan', '5 дан'), ('6 dan', '6 дан'), ('7 dan', '7 дан'), ('8 dan', '8 дан'), ('9 dan', '9 дан'), ('10 dan', '10 дан'), ('Dosyu', 'Досю')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(blank=True, to='user.role'),
        ),
    ]
