# Generated by Django 4.1.7 on 2023-04-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rank_price_alter_role_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
