# Generated by Django 4.1.7 on 2023-04-18 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_delete_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
