# Generated by Django 4.1.7 on 2023-04-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('cities', '0006_alter_address_options_alter_apt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_delete_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Ранг', 'verbose_name_plural': 'Ранги'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.role', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='clubs.club', verbose_name='Клубы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mid_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.rank', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=55, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(choices=[('6 kyu child', '6 кю детский'), ('5 kyu child', '5 кю детский'), ('4 kyu child', '4 кю детский'), ('3 kyu child', '3 кю детский'), ('2 kyu child', '2 кю детский'), ('1 kyu child', '1 кю детский'), ('5 kyu', '5 кю'), ('4 kyu', '4 кю'), ('3 kyu', '3 кю'), ('2 kyu', '2 кю'), ('1 kyu', '1 кю'), ('1 dan', '1 дан'), ('2 dan', '2 дан'), ('3 dan', '3 дан'), ('4 dan', '4 дан'), ('5 dan', '5 дан'), ('6 dan', '6 дан'), ('7 dan', '7 дан'), ('8 dan', '8 дан'), ('9 dan', '9 дан'), ('10 dan', '10 дан'), ('Dosyu', 'Досю')], max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Student', 'Student'), ('Supervisor', 'Supervisor')], max_length=255, verbose_name='Название'),
        ),
    ]
