# Generated by Django 4.1.7 on 2023-05-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_profile_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="next_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_rank",
                to="user.rank",
                verbose_name="Следующий Ранг",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rank",
                to="user.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
