# Generated by Django 4.1.7 on 2023-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_remove_userphoto_photo_remove_userphoto_profile_and_more"),
        ("user", "0023_profile_next_rank_alter_profile_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photos",
            field=models.ManyToManyField(blank=True, to="photos.photo", verbose_name="Фото"),
        ),
    ]
