# Generated by Django 4.1.7 on 2023-07-06 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("6 кю детский", "6 кю детский"),
                            ("5 кю детский", "5 кю детский"),
                            ("4 кю детский", "4 кю детский"),
                            ("3 кю детский", "3 кю детский"),
                            ("2 кю детский", "2 кю детский"),
                            ("1 кю детский", "1 кю детский"),
                            ("5 кю", "5 кю"),
                            ("4 кю", "4 кю"),
                            ("3 кю", "3 кю"),
                            ("2 кю", "2 кю"),
                            ("1 кю", "1 кю"),
                            ("1 дан", "1 дан"),
                            ("2 дан", "2 дан"),
                            ("3 дан", "3 дан"),
                            ("4 дан", "4 дан"),
                            ("5 дан", "5 дан"),
                            ("Нет", "Нет"),
                        ],
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ранг",
                "verbose_name_plural": "Ранги",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "mid_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отчество"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photo/%Y/%m/%d/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=55, verbose_name="Ссылка"),
                ),
                (
                    "next_rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_rank",
                        to="profiles.rank",
                        verbose_name="Следующий Ранг",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rank",
                        to="profiles.rank",
                        verbose_name="Ранг",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
