# Generated by Django 4.1.7 on 2023-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0002_delete_profilephone"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phones",
            field=models.ManyToManyField(
                blank=True, to="phones.phone", verbose_name="Телефоны"
            ),
        ),
    ]
