# Generated by Django 4.1.7 on 2023-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
        ("profiles", "0002_profile_phones"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photos",
            field=models.ManyToManyField(
                blank=True, to="photos.photo", verbose_name="Фото"
            ),
        ),
    ]
