# Generated by Django 4.1.7 on 2023-07-05 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_supervisor_user_is_trainer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_supervisor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_trainer",
        ),
    ]
