# Generated by Django 4.1.7 on 2023-05-11 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_remove_usernotification_profiles_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usernotification",
            old_name="notifications",
            new_name="notification",
        ),
        migrations.RenameField(
            model_name="usernotification",
            old_name="users",
            new_name="user",
        ),
    ]
